baseurl = "http://ecoclimate.org/"
languageCode = "en-us"
title = "ecoClimate - Climatic layers from PMIP3 CMIP5"
# Define how many pages appear per site
paginate = 10

theme = "hugo-theme-chunky-poster"
#paginate = 2
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "people"
    name = "Our Team"
    url = "/people/"
    weight = 2
  [[menu.main]]
    identifier = "downloads"
    name = "Downloads"
    url = "/downloads/"
    weight = 3
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    identifier = "citation"
    name = "Citation"
    url = "/citation/"
    weight = 5
  [[menu.main]]
    identifier = "r-scripts"
    name = "R Scripts"
    url = "/r-scripts/"
    weight = 6


[params]
  author = "ecoClimate Team"
  homepageImage = "img/ecoclimate-background-map-2.jpg"
  share = true
  showLanguageSwitcher = false

  [params.social]
    rss = false
    github = "https://github.com/ecoClimate"
    #email = ""

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
