baseurl = "http://ecoclimate.org/"
languageCode = "en-us"
title = "ecoClimate - Climatic layers from PMIP3 CMIP5"
# Define how many pages appear per site
paginate = 10

theme = "hugo-minimalist-theme"

[params]
    site_author = "ecoClimate Team"
    site_description = "ecoClimate is a project to pre-process and make available the climatic layers from the PMIP3 – CMIP5 projects for macroecologists and biogeographers"
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/avatar-ecoclimate.jpeg"
    header_background = "img/ecoclimate-background-map-2.jpg"
    header_title = "Climatic layers from PMIP3 and CMIP5 projects"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "ecoClimate"
    gplus     = ""
